"""phase_2_models

Revision ID: afbd4a572aa2
Revises: ebc30085658a
Create Date: 2026-07-07 21:23:20.690711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'afbd4a572aa2'
down_revision: Union[str, Sequence[str], None] = 'ebc30085658a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('resource_difficulty_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('estimated_level', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('feature_values', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_extractor_version', sa.String(), nullable=False),
    sa.Column('estimator_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'estimator_version', name='uq_difficulty_resource_estimator')
    )
    op.create_table('resource_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('coverage_status', sa.String(), nullable=False),
    sa.Column('evidence_seconds', sa.Float(), nullable=True),
    sa.Column('extraction_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'topic_id', 'extraction_version', name='uq_resource_topic_version')
    )
    op.create_table('topic_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('normalized_alias', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias')
    )
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['transcript_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'model_name', 'model_version', name='uq_chunk_embedding_model_version')
    )
    op.create_table('resource_feature_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('extractor_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['transcript_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_topic_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_topic_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['transcript_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_topic_id'], ['resource_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_topic_id', 'chunk_id', name='uq_topic_evidence_chunk')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('search_session_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('algorithm_version', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_session_id'], ['search_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_comments_external_id', 'comments', ['external_comment_id'])
    
    # TRUNCATE existing transcript_chunks to safely add new NOT NULL columns.
    # Semantic chunking requires regeneration anyway.
    op.execute('TRUNCATE TABLE transcript_chunks CASCADE')
    
    op.add_column('transcript_chunks', sa.Column('resource_id', sa.UUID(), nullable=False))
    op.add_column('transcript_chunks', sa.Column('start_segment_index', sa.Integer(), nullable=True))
    op.add_column('transcript_chunks', sa.Column('end_segment_index', sa.Integer(), nullable=True))
    op.add_column('transcript_chunks', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('transcript_chunks', sa.Column('chunking_version', sa.String(), nullable=False))
    op.add_column('transcript_chunks', sa.Column('chunking_config_hash', sa.String(), nullable=False))
    op.add_column('transcript_chunks', sa.Column('content_hash', sa.String(), nullable=False))
    op.add_column('transcript_chunks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('transcript_chunks', 'chunk_index',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='chunk_index::integer')
    op.create_unique_constraint('uq_chunk_version_index', 'transcript_chunks', ['transcript_id', 'chunking_version', 'chunking_config_hash', 'chunk_index'])
    op.create_foreign_key(None, 'transcript_chunks', 'resources', ['resource_id'], ['id'])
    op.drop_column('transcript_chunks', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcript_chunks', type_='foreignkey')
    op.drop_constraint('uq_chunk_version_index', 'transcript_chunks', type_='unique')
    op.alter_column('transcript_chunks', 'chunk_index',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('transcript_chunks', 'updated_at')
    op.drop_column('transcript_chunks', 'content_hash')
    op.drop_column('transcript_chunks', 'chunking_config_hash')
    op.drop_column('transcript_chunks', 'chunking_version')
    op.drop_column('transcript_chunks', 'token_count')
    op.drop_column('transcript_chunks', 'end_segment_index')
    op.drop_column('transcript_chunks', 'start_segment_index')
    op.drop_column('transcript_chunks', 'resource_id')
    op.drop_constraint('uq_comments_external_id', 'comments', type_='unique')
    op.drop_table('processing_jobs')
    op.drop_table('resource_topic_evidence')
    op.drop_table('resource_feature_evidence')
    op.drop_table('chunk_embeddings')
    op.drop_table('topic_aliases')
    op.drop_table('resource_topics')
    op.drop_table('resource_difficulty_profiles')
    op.drop_table('topics')
    # ### end Alembic commands ###
