"""phase_1

Revision ID: ebc30085658a
Revises: 1141cf3d35b7
Create Date: 2026-07-06 21:25:26.762458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc30085658a'
down_revision: Union[str, Sequence[str], None] = '1141cf3d35b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_collection_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('sampling_strategy', sa.String(), nullable=True),
    sa.Column('requested_limit', sa.Integer(), nullable=True),
    sa.Column('actual_count', sa.Integer(), nullable=True),
    sa.Column('order_mode', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'segment_index', name='uq_transcript_segment_index')
    )
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_session_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['search_session_id'], ['search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_session_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('query_type', sa.String(), nullable=False),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_session_id'], ['search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_session_id', sa.UUID(), nullable=False),
    sa.Column('search_query_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('provider_rank', sa.Integer(), nullable=True),
    sa.Column('selected_for_ingestion', sa.Boolean(), nullable=True),
    sa.Column('ingestion_priority_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.ForeignKeyConstraint(['search_session_id'], ['search_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_query_id', 'resource_id', name='uq_discovery_query_resource')
    )
    op.add_column('comments', sa.Column('collection_batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comment_collection_batches', ['collection_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'collection_batch_id')
    op.drop_table('discovery_results')
    op.drop_table('search_queries')
    op.drop_table('ingestion_jobs')
    op.drop_table('transcript_segments')
    op.drop_table('comment_collection_batches')
    # ### end Alembic commands ###
